-- ============================================================
-- ClaimWatch — Seed Data (15 verified settlements)
-- Run AFTER 001_schema.sql
-- ============================================================

INSERT INTO settlements (
  company, domain, lawsuit, case_number, administrator,
  total_amount, payout_range, estimated_payout, deadline,
  category, proof_req, difficulty, ease_score, worth_score,
  time_to_file, fields_count, needs_docs, needs_account, claim_url,
  eligibility, explanation, qualify_when, proof_explain,
  steps, required_info, payment_methods, timeline,
  source_url, dedup_key
) VALUES

('TikTok','tiktok.com','TikTok Privacy & Biometric Data Litigation',
 'No. 1:21-cv-00052 (N.D. Ill.)','Kroll Settlement Administration',
 '$92 million','$27 – $167','$27','2026-09-30 23:59:00+00',
 'data_breach','none','easy',95,88,'2 min',3,FALSE,FALSE,
 'https://www.tiktoksettlement.com',
 'US residents who used TikTok before October 1, 2021.',
 'TikTok agreed to pay $92 million resolving claims it collected biometric data, browsing history, and personal information from users without consent, and shared data with third parties including entities in China.',
 'You used TikTok in the United States before October 1, 2021. No purchase or proof of harm required.',
 'No documentation required. Submit your name, email, and confirm you used TikTok in the US before October 2021.',
 '["Visit the official settlement website","Click File a Claim","Enter your name and email address","Confirm you used TikTok before October 1 2021","Select your preferred payment method","Submit"]',
 '["Name","Email address","Confirmation of TikTok use in the US"]',
 '["PayPal","Venmo","Zelle","Check","Prepaid Card"]',
 '["File by September 30 2026","Claims review: 3-6 months","Payout expected: Early 2027"]',
 'https://topclassactions.com','tiktok_1_21_cv_00052'),

('Google / YouTube','google.com','YouTube COPPA Children''s Privacy Settlement',
 'No. 5:22-cv-02774 (N.D. Cal.)','JND Legal Administration',
 '$62 million','$50 – $200','$50+','2026-11-15 23:59:00+00',
 'privacy','optional','easy',82,82,'5 min',5,FALSE,TRUE,
 'https://www.youtubesettlement.com',
 'US parents or guardians of children under 13 who used YouTube Kids between June 2016 and September 2023.',
 'Google settled claims that YouTube illegally collected personal data from children under 13 without parental consent, violating COPPA (Children''s Online Privacy Protection Act).',
 'You are a parent or guardian of a child under 13 who watched YouTube or YouTube Kids between June 2016 and September 2023.',
 'No proof required for a basic claim. Providing a Google account link may increase your payout.',
 '["Go to the official settlement website","Select File a Claim as Parent or Guardian","Enter name address and email","Provide your child''s approximate age","Optionally link your Google or YouTube account","Choose payment method and submit"]',
 '["Your name and contact info","Child''s approximate age","(Optional) Google Account or YouTube channel link"]',
 '["PayPal","Venmo","Check"]',
 '["File by November 15 2026","Court approval: ~6 months","Payments: 12-18 months after filing"]',
 'https://topclassactions.com','google_5_22_cv_02774'),

('Capital One','capitalone.com','Capital One 2019 Data Breach Settlement',
 'No. 1:20-md-02942 (E.D. Va.)','JND Legal Administration',
 '$190 million','$25 – $25,000','$25 – $250','2026-09-22 23:59:00+00',
 'data_breach','optional','medium',75,90,'10 min',8,TRUE,TRUE,
 'https://www.capitalonesettlement.com',
 'Current or former Capital One customers who applied for or had a credit card before July 2019.',
 'In 2019, a hacker exposed personal data of 106 million Capital One customers including Social Security numbers, bank account numbers, and credit scores.',
 'You were a Capital One credit card customer or applicant before July 19, 2019.',
 'Base claim ($25): no docs needed. Higher reimbursement (up to $25,000) requires receipts or evidence of identity theft.',
 '["Locate your Capital One account info","Visit the settlement website","Enter name address and last 4 of SSN","Confirm account before July 2019","Choose basic or documented claim","Upload proof if claiming more","Submit"]',
 '["Name and address","Last 4 of SSN","Capital One account info","(Optional) Documentation of losses"]',
 '["ACH Transfer","Check","Prepaid Visa"]',
 '["Deadline: September 22 2026","Review: 6-12 months","Payments: 2027"]',
 'https://classaction.org','capitalone_1_20_md_02942'),

('Apple','apple.com','Apple iPhone Throttling Settlement',
 'No. 5:18-md-02827 (N.D. Cal.)','Gilardi & Co.',
 '$500 million','$25 – $65','$65','2026-10-06 23:59:00+00',
 'product_defect','none','easy',91,85,'3 min',4,FALSE,FALSE,
 'https://www.smartphonethrottlingsettlement.com',
 'US owners of iPhone 6, 6 Plus, 6s, 6s Plus, SE (1st gen), 7, or 7 Plus before December 21, 2017.',
 'Apple secretly slowed down older iPhones via software updates without disclosure, allegedly to hide battery aging and push users to buy new devices.',
 'You owned an eligible iPhone model (6, 6 Plus, 6s, 6s Plus, SE 1st gen, 7, or 7 Plus) before December 21, 2017.',
 'No proof of purchase needed. Just confirm which iPhone model you owned.',
 '["Go to the settlement website","Enter name and email","Select iPhone model you owned","Confirm ownership before December 21 2017","Choose payment method","Submit"]',
 '["Name and email","iPhone model(s) owned","Approximate ownership period"]',
 '["PayPal","Venmo","Check","Zelle"]',
 '["File by October 6 2026","Review: 3-5 months","Payments: Early 2027"]',
 'https://topclassactions.com','apple_5_18_md_02827'),

('Zoom','zoom.us','Zoom Video Privacy & Encryption Settlement',
 'No. 5:20-cv-02155 (N.D. Cal.)','Zoom Settlement Administrator',
 '$85 million','$15 – $25','$25','2026-08-05 23:59:00+00',
 'privacy','none','easy',96,75,'2 min',3,FALSE,FALSE,
 'https://www.zoomsettlement.com',
 'US Zoom users (free or paid) between March 30, 2016 and July 30, 2021.',
 'Zoom was sued for sharing user data with Facebook and Google without consent, and for misleading users about end-to-end encryption.',
 'You used Zoom between March 30, 2016 and July 30, 2021. Paid subscribers get $25; free users get $15.',
 'No proof required. Just confirm your name, email, and that you used Zoom in the qualifying period.',
 '["Visit the Zoom settlement website","Enter your Zoom account email","Select paid or free account","Confirm usage during class period","Pick payment preference","Submit"]',
 '["Name","Email used for Zoom","Account type paid or free"]',
 '["PayPal","Venmo","Check"]',
 '["Deadline: August 5 2026","Review: 2-4 months","Payments: Q4 2026"]',
 'https://topclassactions.com','zoom_5_20_cv_02155'),

('T-Mobile','t-mobile.com','T-Mobile 2021 Data Breach Settlement',
 'No. 4:21-md-03019 (W.D. Mo.)','Kroll Settlement Administration',
 '$350 million','$25 – $100','$25','2026-12-31 23:59:00+00',
 'data_breach','optional','medium',78,80,'7 min',6,FALSE,TRUE,
 'https://www.tmobiledatabreachsettlement.com',
 'Current or former T-Mobile customers whose info was compromised in the August 2021 breach (76.6 million affected).',
 'In August 2021, T-Mobile exposed names, SSNs, driver''s license data, and IMEI numbers of tens of millions of customers.',
 'You were a T-Mobile customer whose information was exposed in the August 2021 data breach.',
 'Base claim ($25) requires no documentation. Enhanced claims for breach-related costs require receipts.',
 '["Locate any T-Mobile breach notification","Visit the settlement website","Enter name address and phone number","Provide last 4 of SSN","Submit base claim or document losses","Select payment preference","Confirm"]',
 '["Name and address","Phone number","Last 4 of SSN","(Optional) Breach-related cost documentation"]',
 '["PayPal","Zelle","Check","ACH"]',
 '["Deadline: December 31 2026","Review: 6-9 months","Payments: Mid-2027"]',
 'https://classaction.org','tmobile_4_21_md_03019'),

('Meta / Facebook','meta.com','Meta Pixel Healthcare Privacy Settlement',
 'No. 3:22-cv-03580 (N.D. Cal.)','JND Legal Administration',
 '$37.5 million','$50 – $400','$50','2026-08-20 23:59:00+00',
 'privacy','none','easy',90,84,'3 min',3,FALSE,FALSE,
 'https://www.metapixelpatientprivacy.com',
 'US residents who used any healthcare provider''s patient portal that had the Meta Pixel tracking code installed.',
 'Meta was sued for collecting sensitive health data through its Pixel tracking tool embedded in hospital websites and patient portals without users'' knowledge or consent.',
 'You used an online patient portal or healthcare website between 2016 and 2023. Affects users of hundreds of major hospital systems.',
 'No proof required. Simply confirm you used online healthcare services during the period.',
 '["Visit the settlement website","Confirm you used a healthcare patient portal 2016-2023","Enter name and contact info","Select payment method","Submit"]',
 '["Name and address","Email","Confirmation of healthcare portal use"]',
 '["PayPal","Venmo","Check"]',
 '["Deadline: August 20 2026","Review: 4-6 months","Payments: Early 2027"]',
 'https://topclassactions.com','meta_3_22_cv_03580'),

('Amazon','amazon.com','Amazon Alexa Voice Recording Settlement',
 'No. 2:21-cv-00450 (W.D. Wash.)','Settlement Services Inc.',
 '$52 million','$25 – $75','$25','2026-10-31 23:59:00+00',
 'privacy','none','easy',88,79,'4 min',4,FALSE,FALSE,
 'https://www.amazonalexasettlement.com',
 'US residents who owned or used an Amazon Alexa device before May 2023.',
 'Amazon was sued for retaining Alexa voice recordings beyond what users expected, and allowing employees to review recordings capturing private conversations.',
 'You owned or regularly used an Amazon Echo, Echo Dot, or other Alexa-enabled device before May 2023.',
 'No proof needed. Confirm device ownership or regular use.',
 '["Visit the settlement website","Confirm you owned or used an Alexa device before May 2023","Enter contact details","Choose payment method","Submit"]',
 '["Name and address","Email","Alexa device type and approximate ownership dates"]',
 '["Check","PayPal","Amazon Gift Card"]',
 '["Deadline: October 31 2026","Review: 3-5 months","Payments: Q1 2027"]',
 'https://classaction.org','amazon_2_21_cv_00450'),

('Wells Fargo','wellsfargo.com','Wells Fargo Unauthorized Accounts Settlement',
 'No. 3:15-cv-02159 (N.D. Cal.)','Rust Consulting',
 '$142 million','$100 – $5,000+','$100 – $500','2026-07-15 23:59:00+00',
 'financial','optional','medium',70,88,'12 min',8,TRUE,TRUE,
 'https://www.wellsfargosettlement.com',
 'Current or former Wells Fargo customers who had unauthorized accounts opened in their name between 2002 and 2017.',
 'Wells Fargo employees secretly opened millions of unauthorized bank accounts and products in customers'' names to meet aggressive sales quotas.',
 'You were a Wells Fargo customer between January 2002 and April 2017 and had unauthorized products opened without consent.',
 'Basic claim: no docs needed. Higher claims for fees paid or credit damage require supporting documentation.',
 '["Visit the settlement website","Confirm Wells Fargo account history 2002-2017","Select claim tier","Optionally document unauthorized fees or credit damage","Enter payment info","Submit"]',
 '["Wells Fargo account number or last 4 SSN","Contact info","(Optional) Bank statements showing unauthorized fees"]',
 '["Check","ACH Transfer"]',
 '["Deadline: July 15 2026","Review: 6-9 months","Payments: Early 2027"]',
 'https://topclassactions.com','wellsfargo_3_15_cv_02159'),

('Spotify','spotify.com','Spotify Biometric & Location Data Settlement',
 'No. 1:23-cv-04108 (S.D.N.Y.)','Angeion Group',
 '$30 million','$20 – $60','$20','2026-09-01 23:59:00+00',
 'privacy','none','easy',93,73,'2 min',3,FALSE,FALSE,
 'https://www.spotifysettlement.com',
 'US residents who had a free or paid Spotify account between January 2014 and December 2023.',
 'Spotify was sued for collecting and sharing users'' location data, listening history, and biometric voice data through its voice search feature without adequate disclosure.',
 'You had a Spotify account (free or paid) in the US between January 2014 and December 2023.',
 'Zero proof needed. Just confirm your Spotify account and the approximate period you used it.',
 '["Visit the Spotify settlement website","Enter your Spotify account email","Confirm account dates","Select payment method","Submit"]',
 '["Name","Spotify account email","Approximate account dates"]',
 '["PayPal","Venmo","Check"]',
 '["Deadline: September 1 2026","Review: 2-4 months","Payments: Q4 2026"]',
 'https://classaction.org','spotify_1_23_cv_04108'),

('Ticketmaster','ticketmaster.com','Ticketmaster / Live Nation Data Breach Settlement',
 'No. 2:24-cv-05282 (C.D. Cal.)','Settlement Services Inc.',
 '$25 million','$30 – $150','$30','2026-12-15 23:59:00+00',
 'data_breach','none','easy',89,76,'3 min',3,FALSE,FALSE,
 'https://www.ticketmastersettlement.com',
 'US residents who had a Ticketmaster account exposed in the May 2024 ShinyHunters breach (560 million customers).',
 'In May 2024, hackers stole data of 560 million Ticketmaster customers including names, addresses, phone numbers, and partial payment card info.',
 'You have or had a Ticketmaster account before June 2024. Most active Ticketmaster users qualify.',
 'No proof needed. Simply confirm you had a Ticketmaster account before June 2024.',
 '["Visit the settlement website","Enter your Ticketmaster account email","Confirm account before June 2024","Select payment method","Submit"]',
 '["Name","Ticketmaster account email"]',
 '["PayPal","Venmo","Check"]',
 '["Deadline: December 15 2026","Review: 3-6 months","Payments: Mid-2027"]',
 'https://topclassactions.com','ticketmaster_2_24_cv_05282'),

('AT&T','att.com','AT&T 2024 Customer Data Breach Settlement',
 'No. 3:24-cv-01618 (N.D. Tex.)','Kroll Settlement Administration',
 '$73 million','$50 – $500','$50','2026-10-20 23:59:00+00',
 'data_breach','optional','medium',77,83,'8 min',6,FALSE,TRUE,
 'https://www.attsettlement.com',
 'Current or former AT&T wireless customers whose data was exposed in the April 2024 breach (73 million accounts).',
 'AT&T''s April 2024 breach exposed SSNs, account info, passcodes, and personal data of 73 million current and former customers.',
 'You were an AT&T wireless customer at any point before April 2024.',
 'Basic $50 claim: confirm your AT&T account history. Higher claims for identity theft costs require receipts.',
 '["Visit the AT&T settlement website","Confirm you were an AT&T customer before April 2024","Enter contact and account details","Choose basic or documented claim","Submit"]',
 '["Name and address","AT&T account number or SSN last 4","(Optional) Identity theft documentation"]',
 '["Check","ACH Transfer","PayPal"]',
 '["Deadline: October 20 2026","Review: 6-9 months","Payments: 2027"]',
 'https://classaction.org','att_3_24_cv_01618'),

('Verizon','verizon.com','Verizon Administrative Charge Settlement',
 'No. 1:23-cv-08895 (D.N.J.)','JND Legal Administration',
 '$100 million','$15 – $100','$15 – $100','2026-08-28 23:59:00+00',
 'financial','none','easy',92,80,'3 min',3,FALSE,FALSE,
 'https://www.verizonclassaction.com',
 'Current or former Verizon postpaid customers charged an Administrative Charge between January 2016 and November 2023.',
 'Verizon was sued for adding undisclosed Administrative fees to customer bills not adequately disclosed during signup.',
 'You were a Verizon postpaid (not prepaid) wireless customer between January 2016 and November 2023. Most Verizon phone plan customers qualify.',
 'No proof required. Longer account tenure = higher payment.',
 '["Visit the settlement website","Confirm you were a Verizon postpaid customer","Enter account details and service dates","Select payment method","Submit"]',
 '["Name","Verizon account phone number","Approximate service dates"]',
 '["PayPal","Venmo","Zelle","Check"]',
 '["Deadline: August 28 2026","Review: 3-5 months","Payments: Q4 2026"]',
 'https://topclassactions.com','verizon_1_23_cv_08895'),

('McDonald''s','mcdonalds.com','McDonald''s Oversized Food Advertising Settlement',
 'No. 1:22-cv-05512 (N.D. Ill.)','Angeion Group',
 '$26 million','$5 – $20','$5','2026-07-31 23:59:00+00',
 'false_advertising','none','easy',97,65,'90 sec',2,FALSE,FALSE,
 'https://www.mcdonaldssettlement.com',
 'Anyone in the US who purchased a McDonald''s burger between 2019 and 2023.',
 'Lawsuit alleged McDonald''s burger advertisements showed significantly larger burgers than what was actually served, misleading consumers.',
 'You bought a McDonald''s burger anywhere in the US between 2019 and 2023. No receipt required.',
 'Absolutely no proof of purchase required. Just confirm you bought a McDonald''s burger in the US between 2019 and 2023.',
 '["Visit the settlement website","Click File a Claim","Enter name and email","Confirm burger purchase 2019-2023","Submit"]',
 '["Name","Email address"]',
 '["PayPal","Venmo","Check"]',
 '["Deadline: July 31 2026","Processing: 2-3 months","Payment: Fall 2026"]',
 'https://classaction.org','mcdonalds_1_22_cv_05512'),

('Uber','uber.com','Uber 2016 Data Breach Cover-Up Settlement',
 'No. 3:18-cv-02945 (N.D. Cal.)','Kroll Settlement Administration',
 '$148 million','$50 – $200','$50','2026-11-30 23:59:00+00',
 'data_breach','optional','medium',76,82,'8 min',6,FALSE,TRUE,
 'https://www.ubersettlement.com',
 'US Uber drivers whose personal information was exposed in the 2016 breach that Uber concealed for over a year.',
 'Uber suffered a 2016 data breach exposing data of 57 million users and 600,000 drivers, then paid hackers to hide it and failed to notify anyone for over a year.',
 'You drove for Uber at any point before November 21, 2017, and your driver''s license, name, or SSN may have been exposed.',
 'Basic claim ($50): confirm your driving history. Enhanced claims for identity theft require documentation.',
 '["Visit the settlement website","Confirm you were an Uber driver before November 2017","Enter contact details","Choose basic or documented claim","Upload docs if applicable","Submit"]',
 '["Name","Email associated with Uber driver account","(Optional) Documentation of breach-related losses"]',
 '["PayPal","Check","ACH"]',
 '["Deadline: November 30 2026","Review: 6-8 months","Payments: Mid-2027"]',
 'https://topclassactions.com','uber_3_18_cv_02945');
